POST http://127.0.0.1:8000/api/appointments
Content-Type: application/json

{
    "id": "au5o",
    "patient": 2,
    "date_appointment": "2023-04-23",
    "hours_appointment": "10:00"
}

###
GET http://127.0.0.1:8000/api/patients

###
GET http://127.0.0.1:8000/api/patients/1

###
GET http://127.0.0.1:8000/api/clinics/1
###
GET http://127.0.0.1:8000/api/clinics


###
GET http://127.0.0.1:8000/api/doctors/1
###
GET http://127.0.0.1:8000/api/doctors

###
GET http://127.0.0.1:8000/api/appointments/1

###
GET http://127.0.0.1:8000/api/appointments

###
GET http://127.0.0.1:8000/api/patient/ficha-medica/1

####
POST http://127.0.0.1:8000/api/patients
Content-Type: application/json

{
    "nome": "carlos",
    "sexo": "masculino",
    "genero": "masculino",
    "data_nascimento": "10/04/2010",
    "rg": "10/04/2010",
    "cpf":"455453464",
    "passaporte": "03485340593",
    "nacionalidade": "brasileria",
    "naturalidade": "rio de janeiro",
    "nascido_vivo": "10/04/2010",
    "cns": "353535353",
    "numero": "175",
    "localidade": "rua doutor renato",
    "bairro": "Austin",
    "cidade": "Nova Iguaçu",
    "estado": "Rio de Janeiro",
    "uf": "RJ"
}

###
PATCH  http://127.0.0.1:8000/api/appointments/2

{
    "id": 90
}

###
DELETE  http://127.0.0.1:8000/api/appointments/1
